license_id: hdx-odc-odbl
methodology: Other
methodology_other: A deep learning model was trained to determine the footprints of buildings from high resolution satellite imagery. An accompanying [technical report](https://arxiv.org/abs/2107.12283) describes the methodology used to generate the first version of the dataset. Further improvements were made for the subsequent versions, v2 and v3.
caveats:
  "Despite having a diverse set of training data, some scenarios are challenging for the building detection pipeline, including:  \n  \n

  1) geological or vegetation features which can be confused with built structures;  \n
  2) settlements with many contiguous buildings not having clear delineations;  \n
  3) areas characterised by small buildings, which can appear only a few pixels wide at the given image resolution;  \n
  4) rural or desert areas, where buildings constructed with natural materials tend to visually blend into the surrounding area;  \n
  5) areas with high-rise buildings: our model is trained to detect building rooftop rather than base and as a result, depending on satellite image's viewing angle, roofs of high rise buildings jump around which makes it challenging to track buildings across a stack of imagery in a given location.  \n  \n

  See the [technical report](https://arxiv.org/abs/2107.12283) for more details."
dataset_source: Google Earth imagery
package_creator: HDX Data Systems Team
dataset_date: "[2023-05-30T00:00:00 TO 2023-05-30T23:59:59]"
private: False
maintainer: maxmalynowsky
owner_org: google-open-buildings
data_update_frequency: -2
notes:
  "This large-scale open dataset consists of outlines of buildings derived from high-resolution 50 cm satellite imagery. It contains 1.8B building detections in Africa, Latin America, Caribbean, South Asia and Southeast Asia. The inference spanned an area of 58M kmÂ² and was carried out during May 2023.  \n  \n

  Each building in this dataset includes a polygon describing its footprint size on the ground and a confidence score indicating how sure this is a building. There is no information about the type of building, its street address, or any details other than its geometry.  \n  \n

  The HDX team curates these datasets at [Google Open Buildings (by HDX)](https://data.humdata.org/organization/google-open-buildings) using international boundaries from the UN Geospatial Hub.  \n  \n

  For more details, see the official website of the [Open Buildings dataset](https://sites.research.google/gr/open-buildings/)."
